### ISSUE TITLE
Roadmap dashboard :rocket:

### ISSUE THREAD

**Issue by edobrb** [twinlogix/mondrian-framework#142]
- [x] Stable `2.0.x` release (Q1 2024)
   - [x] #76 
   - [x] #210 
   - [x] #211
   - [x] #62 
   - [x] #230
   - [x] #224 
   - [x] #225 
   - [x] #227 
   - [x] #228
 - [ ] Stable `2.1.0` release (Q3 2024)
   - [x] #168 
   - [x] #200
   - [x] #248
 - [ ] Stable `3.0.x` release (unknown date)
   Candidate features:
   - [ ] serve a module as grpc endpoint
   - [ ] support for streaming events (graphql subscription / sse / websocket)
   - [ ] #226 
   - [x] #219
   - [ ] #229
